import os
import tweepy
import requests
from datetime import datetime
import time
import random
from urllib.parse import quote

# === Konfigurasi ===
api_key = os.getenv("TWITTER_API_KEY")
api_secret = os.getenv("TWITTER_API_SECRET")
access_token = os.getenv("TWITTER_ACCESS_TOKEN")
access_token_secret = os.getenv("TWITTER_ACCESS_TOKEN_SECRET")
bearer_token = os.getenv("TWITTER_BEARER_TOKEN")
target_link = os.getenv("TARGET_LINK", "https://example.com")  # Ganti default jika perlu

# Autentikasi Twitter
client = tweepy.Client(
    bearer_token=bearer_token,
    consumer_key=api_key,
    consumer_secret=api_secret,
    access_token=access_token,
    access_token_secret=access_token_secret,
    wait_on_rate_limit=True
)

auth = tweepy.OAuth1UserHandler(api_key, api_secret, access_token, access_token_secret)
api = tweepy.API(auth)

# === Daftar topik trending untuk inspirasi ===
topics = [
    "AI", "tech", "future", "innovation", "science", "coding", "programming",
    "robot", "machine learning", "space", "crypto", "web3", "nft", "gaming"
]

# === 1. Ambil Trending Hashtag dari Twitter (lokasi: Worldwide) ===
def get_trending_hashtags():
    try:
        trends = api.get_place_trends(id=1)  # id=1 adalah Worldwide
        hashtags = []
        for trend in trends[0]["trends"]:
            if trend["name"].startswith("#") and len(hashtags) < 5:
                hashtags.append(trend["name"])
        return hashtags[:3]  # ambil 3 teratas
    except:
        return ["#AI", "#Tech", "#Future"]  # fallback

# === 2. Generate gambar via Craiyon (gratis) ===
def generate_image(prompt):
    url = "https://api.craiyon.com/v3"
    data = {
        "prompt": prompt
    }
    headers = {
        "Content-Type": "application/json"
    }
    try:
        print("Generating image with Craiyon...")
        response = requests.post(url, json=data, headers=headers, timeout=180)
        if response.status_code == 200:
            images = response.json().get("images", [])
            if images:
                img_data = requests.get(images[0], timeout=30).content
                filename = f"generated_image_{int(time.time())}.png"
                with open(filename, "wb") as f:
                    f.write(img_data)
                return filename
    except Exception as e:
        print("Image generation failed:", e)
    return None

# === 3. Buat tweet menarik dengan trending hashtag ===
def create_tweet():
    topic = random.choice(topics)
    mood = random.choice([
        "Mind-blowing",
        "This will change everything",
        "You won't believe this",
        "The future is here",
        "Wait until you see this"
    ])
    hashtags = get_trending_hashtags()
    hashtag_str = " ".join(hashtags)
    
    tweet_text = f"""
{mood} {topic} concept! 🤯

Generated by AI. What do you think?

{hashtag_str}
    """.strip()
    
    return tweet_text, f"{topic} futuristic AI art"

# === 4. Auto-reply ke tweet utama dengan link ===
def reply_with_link(tweet_id):
    reply_text = f"Want to learn how this was made? 👉 {target_link}"
    try:
        client.create_tweet(text=reply_text, in_reply_to_tweet_id=tweet_id)
        print("Replied with link!")
    except Exception as e:
        print("Reply failed:", e)

# === 5. Main Function ===
def main():
    print("🚀 Starting Twitter Bot...")
    
    # Buat tweet
    tweet_text, image_prompt = create_tweet()
    print("Tweet:", tweet_text)
    print("Image prompt:", image_prompt)
    
    # Generate gambar
    image_file = generate_image(image_prompt)
    if not image_file:
        print("❌ Failed to generate image. Exiting.")
        return
    
    # Upload gambar dan post tweet
    try:
        media = api.media_upload(image_file)
        response = client.create_tweet(text=tweet_text, media_ids=[media.media_id])
        tweet_id = response.data["id"]
        print("✅ Tweet posted successfully!")
        
        # Balas dengan link
        time.sleep(5)  # Jeda sebelum reply
        reply_with_link(tweet_id)
        
        # Hapus file gambar
        os.remove(image_file)
        
    except Exception as e:
        print("❌ Tweet failed:", e)

if __name__ == "__main__":
    main()
